apiVersion: cert.gardener.cloud/v1alpha1
kind: Certificate
metadata:
  name: gateway-service-tls
  namespace: istio-system
spec:
  commonName: <DOMAIN>
  dnsNames:
    - app.<DOMAIN>
  secretRef:
    name: gateway-service-tls
    namespace: istio-system