apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gateway-service-tls
  # must be stored in the istio-system namespace. ISTIO ingress pod needs access
  namespace: istio-system
spec:
  secretName: gateway-service-tls
  dnsNames: ["<DOMAIN>"]
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer