apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: minimal
  meshConfig:
    defaultConfig:
      holdApplicationUntilProxyStarts: true
    extensionProviders:
    - envoyExtAuthzHttp:
        headersToUpstreamOnAllow:
        - x-mail
        - x-family_name
        - x-given_name
        - x-name
        - x-picture
        - x-role
        includeHeadersInCheck:
        - cookie
        port: "80"
        service: oidc.auth.svc.cluster.local
        includeRequestBodyInCheck:
          maxRequestBytes: 1000000
          allowPartialMessage: true
      name: oidc-http
  components:
    pilot:
      enabled: true
      k8s:
        replicaCount: 2
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          replicaCount: 2
          serviceAnnotations:
              service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
              service.beta.kubernetes.io/aws-load-balancer-type: nlb    
