
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: gateway-app
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: gateway-service-tls
      hosts: ["app.$DOMAIN"]
